/**
 * AI4HF  passport roles
 */
export enum Role {
    STUDY_OWNER = "STUDY_OWNER",
    DATA_SCIENTIST = "DATA_SCIENTIST",
    SURVEY_MANAGER = "SURVEY_MANAGER",
    DATA_ENGINEER = "DATA_ENGINEER",
    DATA_STEWARD = "DATA_STEWARD",
    QUALITY_ASSURANCE_SPECIALIST = "QUALITY_ASSURANCE_SPECIALIST",
    ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN"
}